# This Docker Compose files contains both API and Client services which can be run separately if necessary.

version: '3.9'

services:
 
  API:
    image: salveracr.azurecr.io/sp-api-mix
    build:
      context: ./API
      dockerfile: ./Dockerfile
    ports:
      - 8080:80

  


