# This is a basic workflow to help you get started with Actions

name: AzurePushDocker


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "azuredeploy" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, defaults to `master`.
          ref: 'azuredeploy'
          
      - name: Edit DB connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/API/appsettings.Development.json'
          name: "DefaultConnection"
          connectionstring: ${{ secrets.DEFAULTCONNECTION }}
          
      - name: Edit Blob connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/API/appsettings.Development.json'
          name: "AzureBlobStorage"
          connectionstring: ${{ secrets.AZUREBLOBSTORAGE }}
        
      - uses: azure/docker-login@v1
        name: Login with docker into ACR
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build API/ -t ${{ secrets.REGISTRY_HOST }}/actions-salver
          docker push ${{ secrets.REGISTRY_HOST }}/actions-salver
